[build]
  command = "npm install --legacy-peer-deps && npm run build"
  publish = ".next"

[build.environment]
  GO_VERSION = "1.20"  # Specify a more recent Go version

[[plugins]]
  package = "@netlify/plugin-nextjs"
